---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    exclude_fingerprints:
      - bb8d03b512c3ce99049505e2188058ec
      - fad3255c32ed9fe569023de53a3e2ca0
      - 994c6743fea399f2c7a5da1d664e8b01
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/
