language: python
python:
  - "3.5"

env:
  - TOX_ENV=py35

install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install codeclimate-test-reporter

script:
  - tox

aftr_success:
  - codeclimate-test-reporter --token $CODE_CLIMATE
