language: python
python:
  - "3.5"

env:
  - TOX_ENV=py35

install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install codacy-coverage

script:
  - tox

after_success:
  # Codacy coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
