build: off

environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%/Scripts/pip.exe pip install -U pip"
  - "%PYTHON%/Scripts/pip.exe pip install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe pip install pytest"

test_script:
  - "%PYTHON%/Scripts/py.test -s tests"
